import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom'
import { archiveCountdown, listManaged, listPublic, newCountdown, saveCountdown, slugify, themes } from './lib/countdowns'
import type { Countdown, CountdownDraft } from './lib/countdowns'
import { completeOwnerMagicLink, pb, refreshOwnerSession, requestOwnerMagicLink } from './lib/pocketbase'
import './index.css'

function Shell({ children }: { children: React.ReactNode }) { return <main><header><Link to="/">COUNTDOWN</Link><nav><Link to="/settings">Settings</Link><Link to="/manage">Manage</Link></nav></header>{children}</main> }
function Index() { const [items,setItems]=useState<Countdown[]>([]); useEffect(()=>{listPublic().then(setItems)},[]); return <Shell><section className="library"><p className="eyebrow">PUBLIC LIBRARY</p><h1>Every deadline, in its right form.</h1>{items.length ? <div className="grid">{items.map(x=><Link className="card" to={`/c/${x.slug}`} key={x.id}><small>{themes.find(t=>t.id===x.theme_id)?.name}</small><h2>{x.title}</h2><p>{x.deadline_date} · {x.deadline_time} · {x.timezone}</p></Link>)}</div> : <p className="empty">No public countdowns yet.</p>}</section></Shell> }
function Detail(){const {slug}=useParams();const [item,setItem]=useState<Countdown|null>(null); useEffect(()=>{listPublic().then(items=>setItem(items.find(x=>x.slug===slug)||null))},[slug]); if(!item)return <Shell><section className="panel"><h1>Countdown unavailable</h1></section></Shell>; return <Shell><section className={`timer ${item.theme_id}`}><p className="eyebrow">{themes.find(t=>t.id===item.theme_id)?.name}</p><h1>{item.title}</h1><time>{item.deadline_date} · {item.deadline_time} · {item.timezone}</time><p className="digits">COUNTDOWN</p><p>{item.note}</p></section></Shell>}
function Settings(){const [zone,setZone]=useState(localStorage.getItem('countdown:timezone')||'Asia/Kolkata'); return <Shell><section className="panel"><h1>Settings</h1><p>These preferences affect only how this browser presents deadline context.</p><label>Preferred timezone<input value={zone} onChange={e=>setZone(e.target.value)} /></label><button onClick={()=>localStorage.setItem('countdown:timezone',zone)}>Save preference</button></section></Shell>}
function Manage(){ const [authenticated,setAuthenticated]=useState(pb.authStore.isValid); const [email,setEmail]=useState(''); const [status,setStatus]=useState(''); const [items,setItems]=useState<Countdown[]>([]); const [draft,setDraft]=useState<CountdownDraft>(newCountdown()); const load=()=>listManaged().then(setItems); useEffect(()=>{const q=new URLSearchParams(location.search); const otp=q.get('otp'),id=q.get('otpId'); (otp&&id?completeOwnerMagicLink(id,otp):refreshOwnerSession()).then(ok=>{setAuthenticated(Boolean(ok)); if(ok) load()});},[]); if(!authenticated) return <Shell><section className="panel"><h1>Manage countdowns</h1><p>Use your approved email to receive a secure sign-in link.</p><form onSubmit={async e=>{e.preventDefault(); await requestOwnerMagicLink(email); setStatus('Check your email for a sign-in link.')}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button>Send magic link</button></form><p>{status}</p></section></Shell>; const submit=async(e:FormEvent)=>{e.preventDefault(); await saveCountdown({...draft,slug:slugify(draft.slug||draft.title)}); setDraft(newCountdown()); load()}; return <Shell><section className="manage"><div><p className="eyebrow">OWNER WORKSPACE</p><h1>Manage countdowns</h1><div className="list">{items.map(x=><article key={x.id}><b>{x.title}</b><span>{x.archived?'Archived':'Public'}</span>{!x.archived&&<button onClick={async()=>{await archiveCountdown(x);load()}}>Archive</button>}</article>)}</div></div><form className="panel" onSubmit={submit}><h2>New countdown</h2><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value,slug:slugify(e.target.value)})} required/></label><label>Slug<input value={draft.slug} onChange={e=>setDraft({...draft,slug:slugify(e.target.value)})} required/></label><label>Date<input type="date" value={draft.deadline_date} onChange={e=>setDraft({...draft,deadline_date:e.target.value})} required/></label><label>Time<input type="time" value={draft.deadline_time} onChange={e=>setDraft({...draft,deadline_time:e.target.value})} required/></label><label>Timezone<input value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})} required/></label><label>Design<select value={draft.theme_id} onChange={e=>setDraft({...draft,theme_id:e.target.value as CountdownDraft['theme_id']})}>{themes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><button>Create public countdown</button></form></section></Shell>}
export default function App(){return <BrowserRouter><Routes><Route path="/" element={<Index/>}/><Route path="/c/:slug" element={<Detail/>}/><Route path="/settings" element={<Settings/>}/><Route path="/manage" element={<Manage/>}/><Route path="*" element={<Index/>}/></Routes></BrowserRouter>}
